name: Typescript Kubernetes Stage Deploy

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-rc.*"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.*"

jobs:
  lint-build-test:
    name: Lint, build and test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm install -g @nestjs/cli
      - run: npm run build --if-present
      - run: npm run lint --if-present
      - run: npm test

  generate-pre-release:
    name: Generate pre-release

    runs-on: ubuntu-latest

    needs: lint-build-test

    steps:
      - uses: actions/checkout@v3
      - name: Generate pre-release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: true
